EMAIL_MAX_LENGHT: int = 254
MAX_NAME_LENGHT: int = 150
TAG_MAX_LENGHT: int = 200
TAG_COLOR_MAX_LENGHT: int = 7
RECIPE_NAME_MAX_LENGHT: int = 200
MIN_VALUE_VALIDATOR: int = 1
MAX_VALUE_VALIDATOR: int = 1000
COOKING_MAX_VALUE_VALIDATOR: int = 300
