version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:alpine
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: baracuda1975/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    image: baracuda1975/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
      - backend
      - frontend