# Generated by Django 3.2.15 on 2023-11-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ('recipe',), 'verbose_name': 'Соответствие ингредиента и рецепта', 'verbose_name_plural': 'Таблица соответствия ингредиентов и рецептов'},
        ),
    ]
