# Generated by Django 3.2.15 on 2023-11-16 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231114_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Не допустимое название!', regex='^[a-zA-Zа-яА-ЯЁё\\s]+[\\d]+$')], verbose_name='Hазвание'),
        ),
    ]
