# Generated by Django 3.2.15 on 2023-11-16 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Не допустимое название!', regex='^[а-яА-ЯЁё\\s]+$')], verbose_name='Hазвание'),
        ),
    ]
