# Generated by Django 3.2.15 on 2023-11-16 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='users_subscription_prevent_self_follow',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя пользователя содержит недопустимый символ', regex='^^[a-zA-Zа-яА-ЯЁё]+$')], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя пользователя содержит недопустимый символ', regex='^^[a-zA-Zа-яА-ЯЁё]+$')], verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя содержит недопустимый символ', regex='^^[a-zA-Zа-яА-ЯЁё]+$')], verbose_name='Имя пользователя'),
        ),
    ]
